# -------------------------------------------------------ALGORITHM 1

# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

# Find the sum of all the multiples of 3 or 5 below 1000.


# def get_it(number):
#   multiples = []
#   for i in (1,number):
#     if i % 3 == 0 or i % 5 == 0:
#       multiples.append(i)
#       print(i)
#   return(multiples)

# multiples = get_it(1000)

# def algorithm(multiples):
#   if len(multiples) == 1:
#     print multiples[0]
#   elif len(multiples) == 0:
#     print "something went wrong"
#   else:
#     multiples[0] = multiples[0] + multiples[1]
#     multiples.remove([1])

# algorithm(multiples)

def solve_this(number):
  multiples = []
  for i in range(1,number):
    if (i % 3 == 0) or (i % 5 == 0):
      multiples.append(i)
  # if len(multiples) > 1:
  #   multiples[0] = (multiples[0] + multiples[1])
  #   multiples.remove(multiples[1])
  # print(multiples[0])
  print(sum(multiples))

solve_this(1000)



# -------------------------------------------------------ALGORITHM 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.


# from math import sqrt

def sum_even_fibonnacci(number):
  n1 = 1
  n2 = 1
  n3 = 0
  the_sum = 0
  while n2 < number:
    if ((n1 + n2) % 2 == 0):
      i = (n1+n2)
      the_sum += i
      n3 = n2
      n2 = (n1 + n2)
      n1 = n3
    else:
      n3 = n2
      n2 = (n1+n2)
      n1 = n3
  print(the_sum)


sum_even_fibonnacci(4000000)



# fib_list = [1,1]
# f = 1 #temp variable
# while f <= 4000000:
#   f = fib_list[-1] + fib_list[-2]
#   fib_list.append(f)
# del(fib_list[-1])
# # We have all the fib numbers below 4mil (33 in total)
# # print fib_list

# even_list = []
# for i in fib_list:
#   if i % 2 == 0:
#     even_list.append(i)
# print sum(even_list)



# -------------------------------------------------------ALGORITHM 3
# The prime factors of 13195 are 5, 7, 13 and 29.

# What is the largest prime factor of the number 600851475143 ?
