# ALGORITHM 1

# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

# Find the sum of all the multiples of 3 or 5 below 1000.


# def get_it(number):
#   multiples = []
#   for i in (1,number):
#     if i % 3 == 0 or i % 5 == 0:
#       multiples.append(i)
#       print(i)
#   return(multiples)

# multiples = get_it(1000)

# def algorithm(multiples):
#   if len(multiples) == 1:
#     print multiples[0]
#   elif len(multiples) == 0:
#     print "something went wrong"
#   else:
#     multiples[0] = multiples[0] + multiples[1]
#     multiples.remove([1])

# algorithm(multiples)

def solve_this(number):
  multiples = []
  for i in range(1,number):
    if (i % 3 == 0) or (i % 5 == 0):
      multiples.append(i)
  # if len(multiples) > 1:
  #   multiples[0] = (multiples[0] + multiples[1])
  #   multiples.remove(multiples[1])
  # print(multiples[0])
  print(sum(multiples))

solve_this(1000)



# ALGORITHM 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.





